[2022-02-06 16:53:57,403] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: etl_crawler_drive.get_data scheduled__2022-01-23T00:00:00+00:00 [queued]>
[2022-02-06 16:53:57,411] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: etl_crawler_drive.get_data scheduled__2022-01-23T00:00:00+00:00 [queued]>
[2022-02-06 16:53:57,411] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-02-06 16:53:57,411] {taskinstance.py:1239} INFO - Starting attempt 1 of 1
[2022-02-06 16:53:57,411] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-02-06 16:53:57,420] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): get_data> on 2022-01-23 00:00:00+00:00
[2022-02-06 16:53:57,425] {standard_task_runner.py:52} INFO - Started process 550 to run task
[2022-02-06 16:53:57,427] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'etl_crawler_drive', 'get_data', 'scheduled__2022-01-23T00:00:00+00:00', '--job-id', '11', '--raw', '--subdir', 'DAGS_FOLDER/etl_crawler_drive.py', '--cfg-path', '/tmp/tmp27ehg3tl', '--error-file', '/tmp/tmpusjx4292']
[2022-02-06 16:53:57,428] {standard_task_runner.py:77} INFO - Job 11: Subtask get_data
[2022-02-06 16:53:57,465] {logging_mixin.py:109} INFO - Running <TaskInstance: etl_crawler_drive.get_data scheduled__2022-01-23T00:00:00+00:00 [running]> on host 6c0d1576d516
[2022-02-06 16:53:57,721] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=etl_crawler_drive
AIRFLOW_CTX_TASK_ID=get_data
AIRFLOW_CTX_EXECUTION_DATE=2022-01-23T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-01-23T00:00:00+00:00
[2022-02-06 16:54:32,884] {local_task_job.py:212} WARNING - State of this instance has been externally set to restarting. Terminating instance.
[2022-02-06 16:54:32,886] {process_utils.py:124} INFO - Sending Signals.SIGTERM to group 550. PIDs of all processes in the group: [550]
[2022-02-06 16:54:32,886] {process_utils.py:75} INFO - Sending the signal Signals.SIGTERM to group 550
[2022-02-06 16:55:32,900] {process_utils.py:138} WARNING - process psutil.Process(pid=550, name='airflow task ru', status='sleeping', started='16:53:57') did not respond to SIGTERM. Trying SIGKILL
[2022-02-06 16:55:32,901] {process_utils.py:75} INFO - Sending the signal Signals.SIGKILL to group 550
[2022-02-06 16:55:32,908] {process_utils.py:70} INFO - Process psutil.Process(pid=550, name='airflow task ru', status='terminated', exitcode=<Negsignal.SIGKILL: -9>, started='16:53:57') (550) terminated with exit code Negsignal.SIGKILL
[2022-02-06 16:55:32,908] {standard_task_runner.py:135} ERROR - Job 11 was killed before it finished (likely due to running out of memory)
