[2022-02-06 22:12:16,185] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: testes_dag_airflow_docker.get_data scheduled__2022-01-24T00:00:00+00:00 [queued]>
[2022-02-06 22:12:16,192] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: testes_dag_airflow_docker.get_data scheduled__2022-01-24T00:00:00+00:00 [queued]>
[2022-02-06 22:12:16,192] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-02-06 22:12:16,192] {taskinstance.py:1239} INFO - Starting attempt 1 of 1
[2022-02-06 22:12:16,192] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-02-06 22:12:16,201] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): get_data> on 2022-01-24 00:00:00+00:00
[2022-02-06 22:12:16,205] {standard_task_runner.py:52} INFO - Started process 178 to run task
[2022-02-06 22:12:16,207] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'testes_dag_***_docker', 'get_data', 'scheduled__2022-01-24T00:00:00+00:00', '--job-id', '95', '--raw', '--subdir', 'DAGS_FOLDER/teste_dag_***_docker.py', '--cfg-path', '/tmp/tmpa52jdycf', '--error-file', '/tmp/tmpz9omcqkk']
[2022-02-06 22:12:16,208] {standard_task_runner.py:77} INFO - Job 95: Subtask get_data
[2022-02-06 22:12:16,248] {logging_mixin.py:109} INFO - Running <TaskInstance: testes_dag_***_docker.get_data scheduled__2022-01-24T00:00:00+00:00 [running]> on host 7e930af9dc8c
[2022-02-06 22:12:16,289] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=testes_dag_***_docker
AIRFLOW_CTX_TASK_ID=get_data
AIRFLOW_CTX_EXECUTION_DATE=2022-01-24T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-01-24T00:00:00+00:00
[2022-02-06 22:12:16,290] {python.py:175} INFO - Done. Returned value was: None
[2022-02-06 22:12:16,298] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=testes_dag_***_docker, task_id=get_data, execution_date=20220124T000000, start_date=20220206T221216, end_date=20220206T221216
[2022-02-06 22:12:16,339] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-02-06 22:12:16,364] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
